import type { Aircraft, SeatType } from './model'

const aircrafts: Aircraft[] = [
  {
    model: '737-300',
    manufacturer: 'Boeing',
    wingspan: 28.9,
    cabinWidth: 3.54,
    cabinHeight: 2.2,
    cabinLength: 24.13,
    cargoCapacity: 27.5,
    range: 4444,
    cruiseSpeed: 0.785,
    engineType: 'CFM56-3 Series',
    noiseLevel: '65-70',
  },
  {
    model: '757-200',
    manufacturer: 'Boeing',
    wingspan: 38.05,
    cabinWidth: 3.54,
    cabinHeight: 2.13,
    cabinLength: 43.21,
    cargoCapacity: 43.4,
    range: 7222,
    cruiseSpeed: 0.8,
    engineType: 'RB211',
    noiseLevel: '65-72',
  },
  {
    model: '757-300',
    manufacturer: 'Boeing',
    wingspan: 38.05,
    cabinWidth: 3.54,
    cabinHeight: 2.13,
    cabinLength: 54.47,
    cargoCapacity: 52.5,
    range: 6295,
    cruiseSpeed: 0.8,
    engineType: 'RB211',
    noiseLevel: '65-72',
  },
  {
    model: '747SP',
    manufacturer: 'Boeing',
    wingspan: 59.64,
    cabinWidth: 6.13,
    cabinHeight: 2.41,
    cabinLength: 56.31,
    cargoCapacity: 170,
    range: 12320,
    cruiseSpeed: 0.85,
    engineType: 'Pratt & Whitney JT9D',
    noiseLevel: '70-75',
  },
  {
    model: 'A310',
    manufacturer: 'Airbus',
    wingspan: 43.9,
    cabinWidth: 5.28,
    cabinHeight: 2.54,
    cabinLength: 36.85,
    cargoCapacity: 150,
    range: 8050,
    cruiseSpeed: 0.8,
    engineType: 'GE CF6-80',
    noiseLevel: '65-70',
  },
  {
    model: 'A300',
    manufacturer: 'Airbus',
    wingspan: 44.84,
    cabinWidth: 5.28,
    cabinHeight: 2.54,
    cabinLength: 40.7,
    cargoCapacity: 164,
    range: 7500,
    cruiseSpeed: 0.82,
    engineType: 'PW4000',
    noiseLevel: '65-70',
  },
]

const seats: SeatType[] = [
  {
    id: 'ECON-HRTG',
    type: 'Heritage Economy Non-Reclining',
    width: 43,
    height: 88,
    pitch: 70,
    weight: 12,
    productionDate: 1980,
    comfortLevel: 5,
    features: ['Wooden', 'non-reclining', 'minimal cushion'],
  },
  {
    id: 'ECON-CLSC',
    type: 'Classic Economy Plus',
    width: 46,
    height: 92,
    pitch: 78,
    weight: 15,
    productionDate: 1990,
    comfortLevel: 35,
    features: ['Basic padding', 'limited recline', 'extra legroom'],
  },
  {
    id: 'BIZ-RETRO',
    type: 'Retro Business Class Basic',
    width: 49,
    height: 95,
    pitch: 89,
    weight: 22,
    productionDate: 1998,
    comfortLevel: 55,
    features: ['Basic reclining', 'added comfort features'],
  },
  {
    id: 'ECON-MILN',
    type: 'Millennium Economy Reclining',
    width: 45,
    height: 90,
    pitch: 72,
    weight: 16,
    productionDate: 2000,
    comfortLevel: 25,
    features: ['Improved cushion', 'limited recline'],
  },
  {
    id: 'ECON-CONTP',
    type: 'Contemporary Economy Plus',
    width: 47,
    height: 94,
    pitch: 82,
    weight: 18,
    productionDate: 2010,
    comfortLevel: 65,
    features: ['Enhanced padding', 'more legroom'],
  },
  {
    id: 'BIZ-ADV',
    type: 'Advanced Business Class Basic',
    width: 51,
    height: 97,
    pitch: 120,
    weight: 28,
    productionDate: 2005,
    comfortLevel: 80,
    features: ['Premium reclining', 'superior comfort features'],
  },
  {
    id: 'BIZ-NEODLX',
    type: 'Neo Business Class Deluxe',
    width: 53,
    height: 100,
    pitch: 210,
    weight: 32,
    productionDate: 2015,
    comfortLevel: 90,
    features: ['Lie-flat', 'luxury materials', 'maximum comfort'],
  },
  {
    id: 'ECON-FUTR',
    type: 'Future Economy Non-Reclining',
    width: 44,
    height: 89,
    pitch: 73,
    weight: 14,
    productionDate: 2018,
    comfortLevel: 30,
    features: ['State-of-the-art materials', 'non-reclining'],
  },
  {
    id: 'ECON-GENP',
    type: 'Generation Plus Economy',
    width: 48,
    height: 96,
    pitch: 84,
    weight: 20,
    productionDate: 2020,
    comfortLevel: 75,
    features: ['High comfort', 'adjustable legroom'],
  },
  {
    id: 'BIZ-ULTRA',
    type: 'Ultra Business Class',
    width: 54,
    height: 101,
    pitch: 220,
    weight: 35,
    productionDate: 2018,
    comfortLevel: 100,
    features: ['Ultimate lie-flat', 'exclusive luxury features'],
  },
]

export default { aircrafts, seats }
